"""generate a FreeCAD api reference by introspecting the installed build.

runs headless under `freecadcmd`. everything written here is *observed* - real
objects are instantiated and their `PropertiesList` / `getTypeIdOfProperty` /
`getEnumerationsOfProperty` read back - so the result is exactly as correct as
the FreeCAD it ran against and cannot drift from it.

that matters because the two obvious alternatives both fail. the wiki documents
the gui (menus, dialogs, checkboxes) and frequently never names the property
behind a control: a displacement constraint's per-axis freedoms are `xFree` /
`yFree` / `zFree`, which appears nowhere in 2600 pages of it. and a model's
memory of the api is worse still, since property names move between versions
(`Support` -> `AttachmentSupport`). a name either came from this file or from a
live introspection call; it is never recalled.
"""

import inspect
import os

import FreeCAD as App

# `doc.supportedTypes()` only reports types whose module is *loaded*, and
# freecadcmd loads almost nothing by default - without these imports the index
# comes out as App plus Image and nothing else. each is optional: a build missing
# a workbench should still produce the rest of the reference, and say so.
PRELOAD = ("Part", "PartDesign", "Sketcher", "Mesh", "MeshPart", "Points",
           "TechDraw", "Fem", "ObjectsFem", "Draft", "Spreadsheet", "Material",
           "Import", "Assembly", "Measure", "Inspection", "Surface")
# workbenches whose `make*` factories are worth listing whole.
FACTORY_MODULES = ("ObjectsFem", "Draft", "Arch")
# the FEM factories are documented with full property tables rather than just
# named: fcad's own FEM support lives or dies on these, and they are the worst
# served by the wiki.
DETAIL_MODULE = "ObjectsFem"
# TypeIds whose property table earns its space: the ones a script actually
# instantiates. anything else is one addObject + PropertiesList away.
DETAIL_TYPES = (
    "App::DocumentObjectGroup", "App::Link", "App::Part", "App::VarSet",
    "Part::Feature", "Part::Box", "Part::Cylinder", "Part::Sphere",
    "Part::Extrusion", "Part::Cut", "Part::Fuse", "Part::Common",
    "Part::Mirroring", "Part::Refine",
    "PartDesign::Body", "PartDesign::Pad", "PartDesign::Pocket",
    "PartDesign::Revolution", "PartDesign::Fillet", "PartDesign::Chamfer",
    "Sketcher::SketchObject",
    "Assembly::AssemblyObject", "Assembly::JointGroup",
    "TechDraw::DrawPage", "TechDraw::DrawViewPart", "TechDraw::DrawViewDimension",
    "Mesh::Feature", "Fem::FemAnalysis",
)
VALUE_CHARS = 60          # repr() width in the default column
GENERATED = "<!-- generated by `fcad api-docs` from FreeCAD %s. do not hand-edit. -->"
FILES = ("index.md", "typeids.md", "factories.md", "fem.md", "properties.md")


def version():
    return ".".join(App.Version()[:3])


def preload():
    """(loaded, absent) workbench module names."""
    loaded, absent = [], []
    for name in PRELOAD:
        try:
            __import__(name)
            loaded.append(name)
        except Exception:
            absent.append(name)
    return loaded, absent


def _rows(obj):
    """(name, type, default, enum choices) for every property on an object."""
    rows = []
    for prop in sorted(obj.PropertiesList):
        try:
            ptype = obj.getTypeIdOfProperty(prop)
        except Exception:
            ptype = "?"
        try:
            value = repr(getattr(obj, prop, None))[:VALUE_CHARS]
        except Exception:
            value = "?"
        choices = ()
        if ptype == "App::PropertyEnumeration":
            try:
                choices = tuple(obj.getEnumerationsOfProperty(prop))
            except Exception:
                choices = ()
        rows.append((prop, ptype, value, choices))
    return rows


def _table(rows):
    """a markdown property table; the pipe in a repr would break the row."""
    out = ["| property | type | default | enum values |", "|---|---|---|---|"]
    for prop, ptype, value, choices in rows:
        out.append("| `%s` | `%s` | `%s` | %s |"
                   % (prop, ptype, value.replace("|", "\\|"),
                      "`%s`" % ", ".join(choices) if choices else ""))
    return "\n".join(out)


def _section(title, body):
    return "\n## %s\n\n%s\n" % (title, body)


def _signature(fn):
    """the factory's call signature, or "(...)" for a c++ binding with none.

    this is the whole answer for the factories that take a *parent* rather than a
    name - the elmer equations want their solver, a mesh region wants its mesh -
    which no amount of retrying `(doc, name)` will discover."""
    try:
        return str(inspect.signature(fn))
    except (TypeError, ValueError):
        return "(...)"


def _made(doc, fn, name):
    """(object, None) or (None, reason) for one factory call.

    tried `(doc, name)` then `(doc)`, which between them cover every factory that
    creates a free-standing object. the rest need an argument only the caller can
    supply, and are documented by signature instead."""
    for args in ((doc, name[4:]), (doc,)):
        try:
            return fn(*args), None
        except Exception as e:
            reason = str(e)
    return None, reason


def index_doc(loaded, absent):
    parts = ["# FreeCAD %s api reference" % version(),
             "\ngenerated by `fcad api-docs` from the FreeCAD on this machine. "
             "every name below was read off a real object, never transcribed, so "
             "it describes this build and no other.\n",
             "\n| file | contents |", "|---|---|",
             "| `typeids.md` | every TypeId `doc.addObject()` accepts |",
             "| `factories.md` | the `make*` functions each workbench exposes |",
             "| `fem.md` | every `ObjectsFem` maker + its full property table |",
             "| `properties.md` | property tables for commonly used TypeIds |",
             "\nworkbenches loaded: %s" % ", ".join(loaded)]
    if absent:
        parts.append("\nnot available on this build (so absent from the index "
                     "below): %s" % ", ".join(absent))
    return "\n".join(parts) + "\n"


def typeids_doc(doc):
    groups = {}
    for tid in sorted(doc.supportedTypes()):
        groups.setdefault(tid.split("::")[0], []).append(tid)
    total = sum(len(v) for v in groups.values())
    out = [GENERATED % version(), "# TypeIds accepted by `doc.addObject()`",
           "\n%d types in %d modules on this build." % (total, len(groups))]
    for mod in sorted(groups):
        out.append(_section("%s (%d)" % (mod, len(groups[mod])),
                            "\n".join("- `%s`" % t for t in groups[mod])))
    return "\n".join(out) + "\n"


def factories_doc():
    """the `make*` helpers per workbench.

    these are the supported way to build a workbench's objects: a factory wires
    up the python feature class behind the object, which a bare `addObject` of
    the same TypeId does not."""
    out = [GENERATED % version(), "# workbench factory functions"]
    for modname in FACTORY_MODULES:
        try:
            mod = __import__(modname)
        except Exception as e:
            out.append(_section(modname, "not available on this build (%s)" % e))
            continue
        names = sorted(n for n in dir(mod)
                       if n.startswith("make") and callable(getattr(mod, n)))
        out.append(_section(
            "%s (%d makers)" % (modname, len(names)),
            "\n".join("- `%s%s`" % (n, _signature(getattr(mod, n)))
                      for n in names)))
    return "\n".join(out) + "\n"


def fem_doc(doc):
    try:
        factory = __import__(DETAIL_MODULE)
    except Exception as e:
        return "%s\n# FEM\n\n%s unavailable: %s\n" % (
            GENERATED % version(), DETAIL_MODULE, e)
    out = [GENERATED % version(), "# FEM objects (%s)" % DETAIL_MODULE,
           "\neach section is a real object made by the named factory on this "
           "build, with its properties as observed."]
    for name in sorted(n for n in dir(factory) if n.startswith("make")):
        fn = getattr(factory, name)
        sig = _signature(fn)
        obj, err = _made(doc, fn, name)
        if obj is not None:
            out.append(_section("`%s%s` -> `%s`" % (name, sig, obj.TypeId),
                                _table(_rows(obj))))
        else:
            # needs an argument only a caller has (a solver, a mesh, an
            # analysis), so the signature is the useful documentation.
            out.append(_section("`%s%s`" % (name, sig),
                                "takes an argument this generator cannot "
                                "supply, so no property table: %s" % err))
    return "\n".join(out) + "\n"


def properties_doc(doc):
    out = [GENERATED % version(), "# property tables for common TypeIds"]
    supported = set(doc.supportedTypes())
    for tid in DETAIL_TYPES:
        if tid not in supported:
            out.append(_section("`%s`" % tid, "not available on this build."))
            continue
        try:
            obj = doc.addObject(tid, tid.split("::")[-1])
        except Exception as e:
            out.append(_section("`%s`" % tid, "could not instantiate: %s" % e))
            continue
        out.append(_section("`%s`" % tid, _table(_rows(obj))))
    return "\n".join(out) + "\n"


def generate(out_dir):
    """write the reference into out_dir; returns the paths written.

    each generator gets a throwaway document because instantiating hundreds of
    objects (several of which recompute on creation) in one document is both
    slower and a chance for one workbench's failure to poison another's."""
    loaded, absent = preload()
    os.makedirs(out_dir, exist_ok=True)
    docs = {"index.md": lambda d: index_doc(loaded, absent),
            "typeids.md": typeids_doc, "factories.md": lambda d: factories_doc(),
            "fem.md": fem_doc, "properties.md": properties_doc}
    written = []
    for fname in FILES:
        doc = App.newDocument("apidocs")
        try:
            text = docs[fname](doc)
        finally:
            App.closeDocument(doc.Name)
        path = os.path.join(out_dir, fname)
        with open(path, "w") as f:
            f.write(text)
        written.append(path)
    return written


def main():
    out_dir = os.environ.get("FCAD_API_OUT") or "api"
    written = generate(out_dir)
    print("api-docs ok: FreeCAD %s -> %s (%d files)"
          % (version(), out_dir, len(written)))
